ALTER TABLE FLIGHT ADD num_pass INTEGER
CHECK (num_pass >=0);

ALTER TABLE AGENCY ADD num_book INTEGER
CHECK (num_book >=0);

CREATE TRIGGER increase_passengers_and_reservations ON BOOKING
FOR INSERT
AS
UPDATE FLIGHT
	SET num_pass = ISNULL(num_pass,0) + (SELECT COUNT(1) FROM INSERTED WHERE FLIGHT_NUMBER = FNUMBER)
	WHERE FNUMBER IN (SELECT FLIGHT_NUMBER FROM INSERTED) 
UPDATE AGENCY
	SET num_book = ISNULL(num_book,0) + (SELECT COUNT(1) FROM INSERTED WHERE AGENCY = NAME)
	WHERE NAME IN (SELECT AGENCY FROM INSERTED)


CREATE TRIGGER decrease_passengers_and_reservations ON BOOKING
FOR DELETE
AS
UPDATE FLIGHT
	SET num_pass = num_pass - (SELECT COUNT(1) FROM DELETED WHERE FLIGHT_NUMBER = FNUMBER)
	WHERE FNUMBER IN (SELECT FLIGHT_NUMBER FROM DELETED) 
UPDATE AGENCY
	SET num_book = num_book - (SELECT COUNT(1) FROM DELETED WHERE AGENCY = NAME)
	WHERE NAME IN (SELECT AGENCY FROM DELETED)

CREATE TRIGGER increase_decrease_number_of_passengers ON BOOKING
FOR UPDATE
AS
IF EXISTS (SELECT 1 FROM INSERTED WHERE STATUS = 1) AND EXISTS (SELECT 1 FROM DELETED WHERE STATUS = 0)
BEGIN
	UPDATE FLIGHT
	SET num_pass = ISNULL(num_pass,0) + (SELECT COUNT(1) FROM INSERTED WHERE FLIGHT_NUMBER = FNUMBER)
	WHERE FNUMBER IN (SELECT FLIGHT_NUMBER FROM INSERTED) 
END
IF EXISTS (SELECT 1 FROM INSERTED WHERE STATUS = 0) AND EXISTS (SELECT 1 FROM DELETED WHERE STATUS = 1)
BEGIN
	UPDATE FLIGHT
	SET num_pass = num_pass - (SELECT COUNT(1) FROM DELETED WHERE FLIGHT_NUMBER = FNUMBER)
	WHERE FNUMBER IN (SELECT FLIGHT_NUMBER FROM DELETED) 
END