INSERT INTO CLASSES VALUES ('Nelson','bb', 'UK', 9, 16, 34000)
INSERT INTO SHIPS VALUES('Nelson', 'Nelson', 1927)
INSERT INTO SHIPS VALUES('Rodney', 'Nelson', 1927)


DELETE FROM SHIPS WHERE SHIPS.NAME IN (SELECT OUTCOMES.SHIP FROM OUTCOMES WHERE OUTCOMES.RESULT = 'sunk')

UPDATE CLASSES SET BORE *= 2.5
UPDATE CLASSES SET DISPLACEMENT *= 1.1