SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES)

SELECT DISTINCT CLASS
FROM SHIPS, (SELECT RESULT, SHIP FROM OUTCOMES WHERE RESULT = 'sunk') r
WHERE r.SHIP = NAME AND r.RESULT in (SELECT RESULT FROM OUTCOMES)

SELECT  SHIPS.NAME, SHIPS.CLASS
FROM SHIPS, CLASSES
WHERE CLASSES.CLASS = SHIPS.CLASS AND BORE = 16

SELECT BATTLES.NAME
FROM BATTLES, OUTCOMES, (SELECT NAME FROM SHIPS WHERE CLASS = 'Kongo') s
WHERE BATTLES.NAME = OUTCOMES.BATTLE AND s.NAME = OUTCOMES.SHIP

SELECT SHIPS.CLASS, SHIPS.NAME
FROM SHIPS, CLASSES p
WHERE p.CLASS = SHIPS.CLASS AND p.NUMGUNS >= ALL(SELECT NUMGUNS FROM CLASSES WHERE BORE = p.BORE)
ORDER BY SHIPS.CLASS

