SELECT ADDRESS
FROM studio
WHERE name='Disney' 

SELECT BIRTHDATE
FROM MOVIESTAR
WHERE name='Jack Nicholson'

SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR = 1980 OR MOVIETITLE = 'Knight'

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > 10000000

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M' OR ADDRESS = ' Prefect Rd.'
