SELECT MOVIE.TITLE, MOVIEEXEC.NAME
FROM MOVIE JOIN MOVIEEXEC ON CERT# = PRODUCERC# AND MOVIEEXEC.NAME = 'George Lucas'

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIE, MOVIEEXEC, STARSIN 
WHERE MOVIE.PRODUCERC# = MOVIEEXEC.CERT# AND STARSIN.MOVIETITLE = MOVIE.TITLE AND STARNAME = 'Harrison Ford'

SELECT DIStINCT MOVIE.STUDIONAME, STARSIN.STARNAME
FROM MOVIE JOIN STARSIN ON MOVIETITLE = TITLE
ORDER BY STUDIONAME

SELECT DISTINCT STARNAME, NETWORTH, MOVIE.TITLE
FROM MOVIE, MOVIEEXEC, STARSIN 
WHERE MOVIE.PRODUCERC# = MOVIEEXEC.CERT# AND STARSIN.MOVIETITLE = MOVIE.TITLE AND MOVIEEXEC.NETWORTH >= ALL(SELECT NETWORTH FROM MOVIEEXEC)

SELECT DISTINCT MOVIESTAR.NAME
FROM STARSIN JOIN MOVIESTAR ON MOVIESTAR.NAME != ALL(SELECT STARSIN.STARNAME FROM STARSIN) 