SELECT *
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS

SELECT *
FROM SHIPS FULL JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS

SELECT DISTINCT CLASSES.COUNTRY, SHIPS.NAME
FROM SHIPS, OUTCOMES, CLASSES
WHERE SHIPS.NAME != ALL(SELECT SHIP FROM OUTCOMES) AND SHIPS.CLASS = CLASSES.CLASS
ORDER BY CLASSES.COUNTRY

SELECT SHIPS.NAME AS 'Ship Name'
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS AND CLASSES.NUMGUNS >= 7 AND SHIPS.LAUNCHED = 1916

SELECT DISTINCT OUTCOMES.SHIP, BATTLES.NAME, BATTLES.DATE
FROM OUTCOMES JOIN BATTLES ON OUTCOMES.RESULT = 'sunk' AND BATTLES.NAME = OUTCOMES.BATTLE
ORDER BY BATTLES.NAME

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, SHIPS.LAUNCHED
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS AND SHIPS.NAME = SHIPS.CLASS

SELECT c.*
FROM SHIPS s RIGHT JOIN CLASSES c ON s.CLASS = c.CLASS AND s.CLASS is NULL

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS, OUTCOMES.RESULT
FROM CLASSES, SHIPS, OUTCOMES
WHERE SHIPS.CLASS = CLASSES.CLASS AND SHIPS.NAME = OUTCOMES.SHIP AND OUTCOMES.BATTLE = 'North Atlantic'