CREATE TABLE PRDCT (model VARCHAR(4), maker VARCHAR(1), type VARCHAR(7));

CREATE TABLE PRNTR (code INT, model VARCHAR(4), price DECIMAL(5, 2));

INSERT INTO PRDCT VALUES('1526', 'A', 'pc');

INSERT INTO PRNTR VALUES(15326, '1223', 12356.12);

ALTER TABLE PRNTR ADD type VARCHAR(6);

ALTER TABLE PRNTR ADD color VARCHAR(1) DEFAULT 'n';

ALTER TABLE PRNTR DROP COLUMN price;

ALTER TABLE PRNTR DROP COLUMN model;

ALTER TABLE PRNTR DROP COLUMN code;

ALTER TABLE PRDCT DROP COLUMN model;

ALTER TABLE PRDCT DROP COLUMN maker;

ALTER TABLE PRDCT DROP COLUMN price;
