CREATE TABLE USERS(number INT, email VARCHAR(30), password VARCHAR(30), date DATE);

CREATE TABLE FRIENDS(firstFR INT, secondFR INT);

CREATE TABLE WALLS(numberOfSender INT, numberOfReciever INT, messageText VARCHAR(100), date DATE);

CREATE TABLE GROUPS(number INT, groupName VARCHAR(20), groupDescription VARCHAR(100) DEFAULT NULL);

CREATE TABLE GROUPMEMBERS(groupNumber INT, userNumber INT);

INSERT INTO USERS VALUES(12121, 'fefef@gmail.com', 'mdmdmkd', '2021-05-02')

INSERT INTO FRIENDS VALUES(12121, 12365)

INSERT INTO WALLS VALUES(12121, 12512, 'mdmfmd', 'feffed')

INSERT INTO GROUPS VALUES(12151, 'fjddkl', 'frfefkefl');

INSERT INTO GROUPMEMBERS VALUES(12131, 12121)